### ISSUE TITLE
EXE doesn't open any applications

### ISSUE THREAD

**Issue by fh-thudson** [Slazanger/SMT#100]
I get no errors.  No nothing. 

I unzipped the folder to the hard drive and clicked on launch.exe and smt.exe and nothing ever opened...  Is anyone else having this issue?

**Comment by cbrothers** [comment]
Do you have the .NET Framework installed on your PC?

Slaz mentioned this in his discord server: https://discord.com/channels/546453460531413002/546453460988461072/982920344400703538

but you need this at least to run the tool - https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by Slazanger** [comment]
you need both the net and desktop framework from the above dotnet link
