### ISSUE TITLE
Do you plan to support Chinese clients?

### ISSUE THREAD

**Issue by soalu** [Slazanger/SMT#103]
Do you plan to support Chinese clients?

**Comment by Slazanger** [comment]
I am going to add localisation support for the UI;  the game side is a little more complicated as I need to know the log keywords for certain things

**Comment by goblock2021** [comment]
@Slazanger If you need the Chinese translation, I may help you.

**Comment by Slazanger** [comment]
duplicate of  https://github.com/Slazanger/SMT/issues/106

**Comment by Binkcn** [comment]
I am already starting to do this, although I am not very good at writing C #, the good news is that XAML syntax makes it easy to handle support for multiple languages.
