### ISSUE TITLE
Feature Request: Minimizeable Map-Layout Buttons (down-right corner)

### ISSUE THREAD

**Issue by Dreak183** [Slazanger/SMT#104]
Please make the map layout option menu:

![image](https://user-images.githubusercontent.com/55458977/213929959-ddb0c78e-869a-4777-9579-a79c5c0af2da.png)

 in the down-right corner minimizable, it takes away nearly half of the map space, when you run SMT kinda small as a InGame overlay.

![image](https://user-images.githubusercontent.com/55458977/213930005-5413e21c-4786-4bb4-a6a3-08090aad9c08.png)

And its a feature that you dont need all the time - if you need to change something or look at a specific layout / highlitghting, you can simply open it, choose the option you like and minimize it again.

Unfortently Iam not very expirienced in C#, otherweise I would create a pull request for it :)

**Comment by Slazanger** [comment]
You can already hide it... in the preferences under "Region/Universe" you can untick "Show Toolbox"

I'll add a minimise though to the todo list

**Comment by tehraven** [comment]
@Dreak183 worth noting that SMT has an *actual* overlay feature now and I believe Slaz will be moving the core SMT intel displays to work with that Overlay soon, so your need to put SMT in that small frame above your chat boxes will soon a lot sexier :)

**Comment by tehraven** [comment]
@Dreak183 Overlay is now a core feature so you don't need to have the whole SMT window on top of your client anymore.
