### ISSUE TITLE
Request adding toggle to show A0 sun systems, with an icon like Jove or similar..

### ISSUE THREAD

**Issue by kaos-1** [Slazanger/SMT#108]
It would make travel so much easier if we could get to show systems on route with A0 suns. 
Here is a complete list if considered. https://pastebin.com/KAqP5J43

**Comment by Slazanger** [comment]
The blue sun's are already displayed on the map, the small blue icons in the region's view

**Comment by Slazanger** [comment]
re-open this if what exists doesnt cover it
