### ISSUE TITLE
Feature Request - Disable Jumpbridge Animation

### ISSUE THREAD

**Issue by czer323** [Slazanger/SMT#12]
I've noticed a large increase in CPU usage of the application when they're enabled.  I know it doesn't seem like a large increase, but it's a factor of 5 on a quad core i7 3770k.  I can imagine it has more impact on a cpu with less cores.

Jump Bridge Enabled: 10% Cpu 
Jump Bridge Disabled: 1-2% Cpu 

If it's possible to simply add a toggle to enable/Disable animation, I think that would be the easiest solution.

**Comment by Slazanger** [comment]
I've made some changes to the animation which has dropped the cpu usage here; let me know if its helped
