### ISSUE TITLE
Bug: Overlay freeze on hover

### ISSUE THREAD

**Issue by Evolution0** [Slazanger/SMT#125]
Sometimes you will hover over a node to see which system it is (and the last reported intel) and nothing will appear, on moving your mouse back out of the overlay and trying again it will become unresponsive.

**Comment by EVEJay** [comment]
Do you have any logfiles for this?

Can you give any more information what happened around this? Any specific system or intel that has been reported? Thank you!

**Comment by Evolution0** [comment]
I'll try and get my hands on that next time I get it to do it.

**Comment by Slazanger** [comment]
please re-open if this is still occuring
