### ISSUE TITLE
Feature Request: Danger Zone Z-Order

### ISSUE THREAD

**Issue by Taiphoz** [Slazanger/SMT#132]
Can you please change the Z-Order when rendering the danger zone circles at the moment they overlap some stuff like system names, Ideally they would be under system names, overlay, kills/deaths etc, seeing that a systems has a kill in it or has been alerted to intel is more important that knowing that system is part of my danger zone so it needs to be drawn first under the more important things.

As a Suggestion, rather than drawing the danger zone as a circle around the system which is causing visibility issues, why not render it as  a coloured outline of the system cell(the things yo colour per sov) it could be an outline or a full cell with the danger zone colour, maybe even have an alpha value for it that we can change or a texture kinda like the blue checkerboard used for alliance zov, maybe use one of those checker colours in the danger zone to show the area covered.

![Untitled](https://github.com/Slazanger/SMT/assets/1296694/a73637a9-50e1-4794-830a-1936f37661c3)
Here is a mock up of the checker board idea and the border idea in the same image.

**Comment by Slazanger** [comment]
That's a good idea; the circles only got added as a debug mode so I could ensure the flood fill was working :)

**Comment by Slazanger** [comment]
this was fixed in 1.30
