### ISSUE TITLE
Bug: Wrong sovereignty and weather info

### ISSUE THREAD

**Issue by Ethreix** [Slazanger/SMT#133]
Yesterday was fine, today my entire alliance is gone from the map (CVA in Providence), and the weather data does not reflect actual in-game weather (for example SMT shows storm in XHQ-7V, but there isn't any in-game).

SMT version downloaded latest release yesterday: 122

**Comment by Slazanger** [comment]
the storm data doesnt come from the game and is from a 3rd party site : https://evescoutrescue.com/home/stormtrack.php it shows a storm centred in 9UY4-H  which would flood out to a minor storm in XHQ

**Comment by Ethreix** [comment]
Thanks for clarifying for the weather. Still missing alliance data for some reason though:
![image](https://github.com/Slazanger/SMT/assets/144154331/0613c0b6-d97a-400c-a4e2-393257c3d506)
I tried forcing an ESI update, but that didn't help.  Installed the app yesterday for the first time ever, so it's a clean install.

**Comment by Slazanger** [comment]
that also looks like its missing 4-5 other alliances

**Comment by Slazanger** [comment]
let me look into it; it might be the names end point.. its extra flakey at times

**Comment by Ethreix** [comment]
The alliance is back today.

**Comment by Ethreix** [comment]
The alliance is gone again today.
![image](https://github.com/Slazanger/SMT/assets/144154331/6a7a0f10-05e9-4312-ac5d-45ff4d04036b)

I think it's decided on the startup? Haven't seen the bug appearing or disappearing mid-run.

**Comment by Ethreix** [comment]
Nope, it does change without restarts. CVA's back up again. Also, I noticed the amount of alliances that disappear/reppeat varies. For example there was no PHEW and no CVA, then PHEW was back, but not CVA. Now both CVA and PHEW are back.

**Comment by Slazanger** [comment]
its the resolution of the ID for the owning alliance that's failing; its unfortunately related to this issue : https://github.com/esi/esi-issues/issues/1181

**Comment by Ethreix** [comment]
I see. Well, it is what it is, thanks for looking into it.

**Comment by Slazanger** [comment]
Im looking at a work around

**Comment by Slazanger** [comment]
This will need to change early dec with the update to the eve-scout site

**Comment by Slazanger** [comment]
ive been unable to repro this, please re-open if still happening
