### ISSUE TITLE
Intel stops reporting.

### ISSUE THREAD

**Issue by Taiphoz** [Slazanger/SMT#135]
The last few hours, possibly since last night my intel randomly stops updating, not sure of the cause cant seem to dial it down, when I notice it I have to close the app and reopen, the issue is that I often dont notice until a hostile is landing on grid its almost cost me twice, thankfully iv been a little lucky.

If it helps, I normally run and track two clients, and I often switch between them actively while ratting on both, I was wondering if perhaps the rapid switching is causing it to lose the correct logfile.

Would it be possible to set an inactive timer, something that beeps when no new log entries are detected in a given time frame, this could help in situations like these, like if I set the timer to 5 minutes and nothing appears in intel for 5 minutes then the app beeps to get the user to double check its reporting ?

**Comment by Slazanger** [comment]
did the intel stop reporting ? or the sound stop playing ?

**Comment by Taiphoz** [comment]
intel feed stopped getting updates , I thot it might eb the sound at first
so I poped out the intel feed and pinned and watched it and it stops, no
clue why

**Comment by Slazanger** [comment]
this should be fixed with 1.23; if you notice it still occurring please re-open
