### ISSUE TITLE
status checks cause intel to stop

### ISSUE THREAD

**Issue by Taiphoz** [Slazanger/SMT#137]
I tracked down this bug a bit more, not 100% on it but the last 4 times its stopped reporting intel has been right as some one has typed something like "status >>>" requesting a status check on a given system, Im going to totally remove all ignore stuff to see if that helps , but you might want to check that part of the code.

**Comment by Taiphoz** [comment]
ignore the typo and assume I cant spell. lol

**Comment by Taiphoz** [comment]
just got a successful status check and it didnt freeze, so I think its deff the ignore code.

**Comment by Slazanger** [comment]
thank you for the help repro-ing this; I've been struggling to narrow it down!

**Comment by Slazanger** [comment]
This should be fixed in 1.24
