### ISSUE TITLE
I am receiving this script error when trying to apply my character

### ISSUE THREAD

**Issue by AeriaDiscordiam** [Slazanger/SMT#14]
Script error when applying EVE character for Slazanger's Map Tool 0.52
Unable to type in panel to log in to EVE

![error](https://user-images.githubusercontent.com/34974455/52098313-5778f880-2583-11e9-9e32-64ac161d3b1d.png)

**Comment by PcHelpPros** [comment]
Run the browser batch file located in one of the folders, it's in all caps.
It should fix that issue.

**Comment by BitBaboonSteve** [comment]
As mentioned above this is what the registry file called "Run me first" fixes
