### ISSUE TITLE
Feature Request: Ensure all settings persist across versions

### ISSUE THREAD

**Issue by Taiphoz** [Slazanger/SMT#140]
Basically every time an update comes out we overwrite any changes we have made, meaning we need to go through all the settings make all those changes again, can we get a download that only has the changes in it or some way of installing the update without overwriting our settings and saved colour changes. ?

**Comment by Netzvamp** [comment]
+1

**Comment by DopeEx** [comment]
+1

**Comment by Slazanger** [comment]
This should be fixed with the next release.. from 1.27 onwards (eg upgrading from 1.27 to 1.28) if compatible; the layout and settings will persist across versions.. it may occasionally be reset as per the characters (its happened 3 times in 4 years) but i will try and keep this to a minimum
