### ISSUE TITLE
Missing System.Windows.Interactivity

### ISSUE THREAD

**Issue by afarazit** [Slazanger/SMT#15]
@Slazanger trying to compile the project but can't as using System.Windows.Interactivity is missing on WpfHelpers PasswordBehavior. Where do I find it?

**Comment by afarazit** [comment]
Can you help @Slazanger?

**Comment by Slazanger** [comment]
Hey; missed this.. what version of VS are you using ?

**Comment by afarazit** [comment]
I was using the version before 0.55. Going to check if 0.55 solves that issue

**Comment by Slazanger** [comment]
I upgraded to VS2017 community a while back to use the latest ESI.net; its probably that

**Comment by afarazit** [comment]
@Slazanger those are the error i'm getting
![image](https://user-images.githubusercontent.com/1217574/56666429-8e5b3800-66b4-11e9-9872-7fcb1b4fe10e.png)

**Comment by afarazit** [comment]
Followed this suggestion and solved the issue with System.Windows.Interactivity
https://stackoverflow.com/a/52110697/455934
