### ISSUE TITLE
Jump Bridges is not available 

### ISSUE THREAD

**Issue by MusicmanEve** [Slazanger/SMT#161]
Hello, the bottom find gates is not available. 
What is problem?
![Снимок](https://github.com/Slazanger/SMT/assets/170938244/25957e8f-38fa-48a4-977d-b46df839613c)

**Comment by ChuckNasty92** [comment]
Same issue, import from clipboard isn't working either. Anyone figure out to unlock the inputs for this feature?

**Comment by tehraven** [comment]
@MusicmanEve this is a known issue. Esi being serving for Alexis a lung time ago and CCP has zero interest in fixing it. 

@ChuckNasty92 import still works just follow the instructions on discord.

**Comment by MusicmanEve** [comment]
> @MusicmanEve this is a known issue. Esi been broken for a long time ago and CCP has zero interest in fixing it.
> 
> @ChuckNasty92 import still works just follow the instructions on discord.

Can you help. i saw a instructions 

Open the Structure Browser in-game
Select “Jump Bridges” and “Region”, make sure all services are deselected. (Always do a whole region at a time.)
Create a new chat channel for yourself
Drag and drop the first structure into the chat window as if you were linking it
Hit enter and repeat for every single jump bridge in that region
Right click and “Copy All”
Paste the list in a rich text editor

i tried but i dont know why didnt work

may be i do wrong format 
for example 
Q0OH-V » WX-6UX - Sheriff's Star

**Comment by Slazanger** [comment]
@MusicmanEve it looks like you're not using a rich text editor, as the text should contain some encoding for the structure id etc
