### ISSUE TITLE
ZKB Feed

### ISSUE THREAD

**Issue by Queueyou** [Slazanger/SMT#20]
Updated to 0.58 and ZKB Feed is no longer updating.

Shows ZKillData is checked.  Have tried open/close and check/uncheck

**Comment by Queueyou** [comment]
And just now it started loading like crazy again.  I did nothing but change from intel to ZKB Feed a couple times.  I have noticed that sometimes it's colored for a split second when a new item comes up, but then the list seems to grow/shrink/grow a few times.  Like it's loading/unloading recent stuff.  If you have some server doing it all, perhaps it's reading from it too fast.

**Comment by Slazanger** [comment]
it uses the redisq feed from ZKill.  It only keeps the last 20 minutes of data (I plan to add a config for this).

I'll keep an eye on this to make sure nothing funky is going on though
