### ISSUE TITLE
Unable to add characters

### ISSUE THREAD

**Issue by rupertd** [Slazanger/SMT#23]
Hi there, I've been using earlier releases of SMT for a while and never had any challenges adding characters.  I took at Hiatus from the game and on my return I installed the latest SMT release (59).

I applied the REG fix and proceeded to add characters.  The SMT internal browser spawned, I added the Eve login details and the screen changed as expected to the 'two factor auth' code validation.

I entered the 6 digit auth code and press enter; only to be immediately recycled straight back to the login screen to add my Eve character login details again.  At no point does the CCP AUTHORIZE window appear.

I have completely removed the app and all previous instances from my machine, and removed the REG entries and tried again.  Same result.  I have validated that the BATCH file does write to the registry; so that is working fine.

An interesting result can be achieved by using OLDER character dat files in the 59 release.  The characters still show, and it does follow my system location; but I cannot manipulate travel destinations; so a partial scope exists there somewhere.

I've tried all variations; but cannot add characters at all with the 59 release.  It just cycles the first login challenge screens.

I even set my default browser on the PC back to IE from CHROME (as much as I hate it; but that didn't help either).

Any thoughts? [and thanks for the wonderful tool]

**Comment by LordMrcS** [comment]
Can confirm on this, can't login.  Windows 10/Firefox 72.

https://prnt.sc/qooeh5

**Comment by Slazanger** [comment]
@LordMrcS have you run the batch file ?

**Comment by LordMrcS** [comment]
@Slazanger that did the trick. Thanks!
