### ISSUE TITLE
Intel filter

### ISSUE THREAD

**Issue by JasonMcHe** [Slazanger/SMT#29]
Intel filter for specified words with configuration file *.txt e.g. status
such words cause false alarms, e.g. activated "limit sound to danger zone"

**Comment by Paic** [comment]
There could be a new preference "Ignore Filter" (in the Intel tab) where you put keywords that when matched does not trigger intel / clear events.
@Slazanger any thoughs about this ?

**Comment by Slazanger** [comment]
That's a good idea, seperate ignore from clear
