### ISSUE TITLE
Script error for SSO page

### ISSUE THREAD

**Issue by ericholzer** [Slazanger/SMT#3]
great work!!!

when I try to import a char I receive several script error from the in browser page and even if I press the button to authorize nothing happens

**Comment by Slazanger** [comment]
Hi there.. you need to import the registry settings (just double click on the registry file) it will enable the built in browser to run the latest version of IE..

**Comment by Slazanger** [comment]
I forgot to add, if your building it from source the registry file is located here : https://github.com/Slazanger/SMT/blob/master/RUN%20ME%20FIRST%20SMT%20Built%20in%20Browser%20Fix.reg

**Comment by ericholzer** [comment]
thanks

Da: Slazanger [mailto:notifications@github.com]
Inviato: domenica 13 agosto 2017 23:46
A: Slazanger/SMT <SMT@noreply.github.com>
Cc: ericholzer <ericholzer@live.it>; Author <author@noreply.github.com>
Oggetto: Re: [Slazanger/SMT] Script error for SSO page (#3)


I forgot to add, if your building it from source the registry file is located here : https://github.com/Slazanger/SMT/blob/master/RUN%20ME%20FIRST%20SMT%20Built%20in%20Browser%20Fix.reg

**Comment by ericholzer** [comment]
Hi,

I updated and the SSO now doesnt give errors

But I dont see my char on the software

thanks

Da: Slazanger [mailto:notifications@github.com]
Inviato: domenica 13 agosto 2017 23:46
A: Slazanger/SMT <SMT@noreply.github.com>
Cc: ericholzer <ericholzer@live.it>; Author <author@noreply.github.com>
Oggetto: Re: [Slazanger/SMT] Script error for SSO page (#3)


I forgot to add, if your building it from source the registry file is located here : https://github.com/Slazanger/SMT/blob/master/RUN%20ME%20FIRST%20SMT%20Built%20in%20Browser%20Fix.reg

**Comment by Slazanger** [comment]
do you have a file in the same folder as the app called characters.dat ?

**Comment by Slazanger** [comment]
also, does anything appear in the 3rd dropdown ?

**Comment by ericholzer** [comment]
Yes, I have it

The strange thing is this part

<ESIAccessTokenExpiry>2017-08-14T15:07:50.5592938

The expiry date seems strange

Da: Slazanger [mailto:notifications@github.com]
Inviato: mercoledì 16 agosto 2017 20:46
A: Slazanger/SMT <SMT@noreply.github.com>
Cc: ericholzer <ericholzer@live.it>; Author <author@noreply.github.com>
Oggetto: Re: [Slazanger/SMT] Script error for SSO page (#3)


do you have a file in the same folder as the app called characters.dat ?

**Comment by ericholzer** [comment]
What do you mean for 3rd dropdown?

thanks

Da: Slazanger [mailto:notifications@github.com]
Inviato: mercoledì 16 agosto 2017 20:47
A: Slazanger/SMT <SMT@noreply.github.com>
Cc: ericholzer <ericholzer@live.it>; Author <author@noreply.github.com>
Oggetto: Re: [Slazanger/SMT] Script error for SSO page (#3)


also, does anything appear in the 3rd dropdown ?

**Comment by Slazanger** [comment]
Can you delete that characters.dat file and run it again.  And let me know if it runs. The drops downs are on the top left of the window. The first is the region's, second is system and third is your character list

**Comment by ericholzer** [comment]
Deleting it seems all fine

Thanks

eric

Da: Slazanger [mailto:notifications@github.com]
Inviato: lunedì 21 agosto 2017 00:38
A: Slazanger/SMT <SMT@noreply.github.com>
Cc: ericholzer <ericholzer@live.it>; Author <author@noreply.github.com>
Oggetto: Re: [Slazanger/SMT] Script error for SSO page (#3)


Can you delete that characters.dat file and run it again. And let me know if it runs. The drops downs are on the top left of the window. The first is the region's, second is system and third is your character list
