### ISSUE TITLE
Not all ansiblexes can be verified with ESI

### ISSUE THREAD

**Issue by RMoDOOM** [Slazanger/SMT#30]
Some Ansiblexes need roles to be searchable via ESI or even in-game. Structure browser in-game is the only way to see the items. As a result not all jump gates can be added to the list.

As this is the case for most jump bridges I'm using, please add a way to manually add jump bridges.

**Comment by Slazanger** [comment]
You can already add jump bridges, look at the import from clipboard option...  it imports one per line that it finds in the format : 

<structure id> FromSystem --> ToSystem
