### ISSUE TITLE
ZKB Feed not working

### ISSUE THREAD

**Issue by JM-GH** [Slazanger/SMT#35]
Just installed fresh version of SMT 8.1, was previously using version 7.7.
Could be a coincidence but, the ZKB Feed is not updating or showing on map overlay.
Local time zone on my machine is GMT.

**Comment by JM-GH** [comment]
Getting very patchy entris for ZKB info, only a few for entire universe.

**Comment by JM-GH** [comment]
Just installed fresh version of SMT 8.1, the ZKB Feed is not updating or showing on map overlay.

**Comment by Paic** [comment]
Is this still happening in [1.01](https://github.com/Slazanger/SMT/releases/tag/SMT_101) ?
