### ISSUE TITLE
.85 - Not detecting characters, not playing sound, no documentation on danger zone

### ISSUE THREAD

**Issue by Bemused-Harpy** [Slazanger/SMT#44]
I downloaded .85 and have tried to get it running to play the sound when intel shows someone nearby, but I cannot find where to configure it. I did find the section under preferences but even with the play sound and show danger zone, nothing changes and no sounds are played. It's also seemingly having a hard time detecting my characters too.

Love what you're doing o7
~Bemused Harpy

**Comment by Bemused-Harpy** [comment]
I was able to figure it out.

**Comment by Archetype90** [comment]
What was your solution? Mine had been working fine, but suddenly is not recognizing my characters, and as a result cannot set the danger zone.

**Comment by Slazanger** [comment]
@Archetype90 have you authenticated your characters ?

**Comment by Bemused-Harpy** [comment]
Using the character menu on the right side of the map. The buttons didn’t catch my eye initially as I was focusing on the menu bar for the options. Most recent version is working really well.

**Comment by Slazanger** [comment]
if you dont authenticate the characters it will only find them when you change systems in game

**Comment by Archetype90** [comment]
Thank you 👍 
I authenticated them @Slazanger and that worked. Must have had them recognized before from changing systems.
