### ISSUE TITLE
Can't compile the solution.

### ISSUE THREAD

**Issue by FabioEnne** [Slazanger/SMT#46]
Hello I'm trying to compile the solution but various errors are popping out. 

I'll paste here some of the compiler error:

SsoLogic does not contain a definition for GetTokenV2, CreateAuthenticationUrlV2, GetTokenV2. 

How can I successfully compile the solution? Thanks

**Comment by Slazanger** [comment]
You'll need to grab the version of ESI.Net from my github until the the full v2 auth flow gets implemented and I switch back to the nuget version

**Comment by FabioEnne** [comment]
Ah ok, thank you very much I ws trying to debug the add JumpBridge functionality as I can't import Jumpbridge in this format:

```
Q-EHMJ 3-1  -->  8MG-J6 2-1
LS-JEP 2-1  -->  LX-ZOJ 3-1
Y6-9LF 2-1  -->  1-EVAX 1-1
S-R9J2 2-1  -->  PWPY-4 1-1
W-XY4J 2-1  -->  Y-XZA7 4-1
PWPY-4 1-1  -->  S-R9J2 2-1
Y-XZA7 4-1  -->  W-XY4J 2-1
1-EVAX 1-1  -->  Y6-9LF 2-1
LO5-LN 1-1  -->  UJXC-B 2-1
GL6S-2 1-1  -->  Q-GICU 4-1
A-J6SN 3-1  -->  1PF-BC 4-1
K-YL9T 3-1  -->  C-BHDN 3-1
C-BHDN 3-1  -->  K-YL9T 3-1
UAJ5-K 1-1  -->  J-0KB3 3-1
J-0KB3 3-1  -->  UAJ5-K 1-1
AID-9T 1-1  -->  1ACJ-6 1-1
LPVL-5 3-1  -->  RK-Q51 2-1
G-QTSD 5-1  -->  FB-MPY 1-1
3G-LFX 3-1  -->  F9-FUV 5-1
BY-7PY 4-1  -->  D-OJEZ 2-1
N06Z-Q 3-1  -->  89-JPE 3-1
1ACJ-6 1-1  -->  AID-9T 1-1

Any idea why? I'm copying that and than I click on import from clipboard but nothing happens..
```

**Comment by Slazanger** [comment]
The import format changed with the release of the ansiblex structures..

Its now in the format 

<structureid from> FromSystem --> To

eg
1234567890 Jita --> Obe

you'll need both sides of the gate for the best experience
9231235412 Obe --> Jita

if you dont know the structure ID just use 0 and the route mapping will take you to the system and you have to remember to take the ansiblex gate
