### ISSUE TITLE
Volume not beeing saved

### ISSUE THREAD

**Issue by Sakreton** [Slazanger/SMT#48]
After changing the volume in the Windows volume mixer it will be saved for that session, but after i restarted SMT or my pc it will be back to 100% which is quiet annoying, i am not sure if this is a Windows or SMT problem. :/
Btw SMT is great :D love it

**Comment by Beldiran** [comment]
An in-app volume control would be great.
Having to use Windows to configure the volume is very annoying.
other wise a great App thank you for the work you do.
