### ISSUE TITLE
Feature Request: Customizable Audio Alerts

### ISSUE THREAD

**Issue by Gersdorff** [Slazanger/SMT#49]
It would be nice if there were the possibility to set different freely selectable sounds for different events/alerts.

e.g.: 
- Enemy 5 jumps out - > Sound a 
- Enemy 4 jumps out - > Sound b 
- Status Request - > Sound c

As is possible with the Inteltool IMP, for example.
See: [https://github.com/3vi1/IMP](https://github.com/3vi1/IMP)

Thus, one could already recognize by the played sound whether the enemy is coming closer or flying away, or what alarm it is.

**Comment by Slazanger** [comment]
these are already in the todo list : https://github.com/Slazanger/SMT/projects/1
