### ISSUE TITLE
Request: Store settings in gitignored file

### ISSUE THREAD

**Issue by mathieudevos** [Slazanger/SMT#60]
Hey,

This simple change would allow us to update the application by just copying the contents of the ZIP to our old folder and overwrite everything.

Doing this would always make sure that the settings are not overwritten. Things such a color themes, sounds, alerts, ... wouldn't be cleared every time we end up with an update.

Would increase usability by a massive factor.

(Otherwise super awesome app, keep it up!)

**Comment by Slazanger** [comment]
The settings are already stored outside of the app.. they are in My Documents\SMT\

The version specific files are in their own sub folders, and as features I move the files to the root.. so currently character and jump bridge data will persist across versions.
