### ISSUE TITLE
.95 Dangerzone not distance selector gone.

### ISSUE THREAD

**Issue by natereinhardt** [Slazanger/SMT#61]
Im not sure if it moved or it is gone - im not seeing an spot to select my danger zone.

![image](https://user-images.githubusercontent.com/9617274/98124985-7ce21700-1e79-11eb-8d68-10d84d98a2f6.png)

**Comment by Slazanger** [comment]
This is now per-character in the new character screen

**Comment by natereinhardt** [comment]
Oh awesome. Thanks for the quick response!  Sorry!
