### ISSUE TITLE
No more Intel and jumpbridge after clearing

### ISSUE THREAD

**Issue by maso1337** [Slazanger/SMT#65]
After clearing the bridges, because of overlapping of old and new one, I can not find new bridges.
I try to clear everything also default my settings... it's not working, but then I observe that my Intel is also death and I go to delete the smt folder, load a new one and do the setup and settings. It still not working...

What can I try ?

**Comment by TeRmOPoD** [comment]
yes I have the same trouble that I just did not do it and the registry was cleaned and reinstalled no longer finds the bridges at all and does not lay out the routes after deletion ((

**Comment by Takeiteasyeh** [comment]
This has been broken for over a month now and makes the tool pretty much useless. Do we have an update for this or

**Comment by Slazanger** [comment]
The root issue of this is : https://github.com/esi/esi-issues/issues/1268

You can add the bridges manually, instructions are in the discord pinned messages

**Comment by maso1337** [comment]
ok, but is it also the problem that I have, that the tool does not alert and show any Intel?
All is fine, esi is in character is on the map in the right system but no intel is reconized by SMT..

**Comment by Slazanger** [comment]
Is the game still logging chat channels to file ?  some people seem to think disabling it will make the big tidi fights faster

**Comment by maso1337** [comment]
> Is the game still logging chat channels to file ? some people seem to think disabling it will make the big tidi fights faster.. (it won't)

You're right, my chat wasn't logging to file. I fix the most important problem now. The issue with the JB is ok for now.
Thanks for your help Slazanger!
