### ISSUE TITLE
Intel malfunction on translated system names

### ISSUE THREAD

**Issue by chrRtg** [Slazanger/SMT#7]
If a user uses a non-english Eve client system names dragged to an intel chat will appear with an asterisk attachted to the name. Instead of e.g. "Jita" it becomes "Jita*" and the system name is no longer recognized.

**Comment by Slazanger** [comment]
Could you post one of the local logs ?

**Comment by chrRtg** [comment]
Sure, you're welcome, copy paste from the Intel but I may also take it from the log file on my hard drive if you need.

> [18:56:50] Some Player > <url=showinfo:5//30003350>57-YRU*</url> clr

**Comment by Slazanger** [comment]
Thanks; I've fixed this now; should correctly parse intel.  I've pushed the code changes to github and will make a new build when i get a chance

**Comment by chrRtg** [comment]
whow, much appreciated, will keep an eye on the /releases

**Comment by chrRtg** [comment]
tested, solution confirmed. You may close this issue.

Thanks for the incredible support!
