### ISSUE TITLE
migration to .NET 5.0

### ISSUE THREAD

**Issue by rafaga** [Slazanger/SMT#74]
I'm running a mac eve client do you have plans to migrate this app to .Net 5.0 and make compatible with MacOS ?

**Comment by Slazanger** [comment]
yes, the plan is to move over to .net core 5

**Comment by Yerodin011** [comment]
Any news on this? :)

**Comment by Slazanger** [comment]
been working on it the last couple of days.. eliminating a bunch of stuff that wont work on .net core :)

**Comment by Yerodin011** [comment]
Good news indeed! :)

If I can help somehow to get it running on MacOS after the move I'd be happy to do so.

**Comment by rafaga** [comment]
do you have a fork or a branch , that I can test and debug to help ?

**Comment by Slazanger** [comment]
the initial upgrade is on a new dotnet6_upgrade branch.. the app now works on Windows (although heavily untested and with a ton of compat changes still required)

**Comment by rafaga** [comment]
as expected doesn't run on MacOS becase it has dependencies on Windows Forms or at least is what it says SMT.sln 

```
    <UseWindowsForms>True</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
```

It is not using Windows Forms, This should be removes, if it is being used It needs to be migrated to MAUI ...

**Comment by Slazanger** [comment]
Yeah I only got as far as the upgrade.. consolidated and removed a bunch of stuff, upgraded so I could have a smooth transition onto .net 6..  now the fun of moving it over.

I *think* the only thing winforms is used for is the directory selection for the log folders, so should be a simple switch; the rest is fairly standard WPF

**Comment by rafaga** [comment]
Update: it also throws an error when I restore the NuGet packages, in specific with the package System.ServiceModel.Federation

```
/usr/local/share/dotnet/sdk/6.0.202/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5) : error NETSDK1100: Windows is required to build Windows desktop applications.
Unable to create package spec for project. '/Users/projects/SMT/SMT.csproj'
```

There is any alternative to this package ?

testing on MacOS X 12.3.1

**Comment by Slazanger** [comment]
not yet; im working my way through the compatibility warnings at the moment. The current plan is to get the windows build running as correct as possible on .net 6 and then look at how much needs replacing/rebuilding

**Comment by rafaga** [comment]
Ok I resolved the previous problems ... but there is a roadblock to make it multiplataform with netcore 6.0 ... WPF is not available in MacOS or Linux ... so it is not possible to run SMT in other plataforms besides Windows...

There is alternatives ... like migrating to MAUI or using something like Avalonia.

**Comment by Slazanger** [comment]
Switching to Avalonia is the long term plan; the main two issues are that I use AvalonDock extensively and that the WPF Shapes are too slow for the universe view ( which is why it's a little more complicated with the VisualHosts and separated input handling.. if I use the shapes, because they all inherit from UIElements the layout phase with this many pieces takes a few minutes)

**Comment by Slazanger** [comment]
currently just the net6 branch;  once this is done and back onto the mainline can start the UI conversion.

**Comment by Slazanger** [comment]
ive pulled the .net 6 branch into master and will push 1.10 on .net 6

**Comment by rafaga** [comment]
SMT is now compatible with .net 6 framework
