### ISSUE TITLE
Intel preferences not saving, after moving and updating

### ISSUE THREAD

**Issue by john2288** [Slazanger/SMT#76]
Hello,
A little while ago I had moved the smt folder to another HD after running out of space. Everything was fine, up until I updated the other day.

The intel tab in preferences reset everything to off, the only thing that remained was the old intel channel I thought I had changed a week or 2 ago. (haven't been on in a few weeks)  When I set up my settings again and put in my proper intel channel, everything is fine, until I restart. It reverts everything back.

All the other settings are working properly except that tab. I completely deleted the whole folder and redownloaded, but everything was still there.

I assume this is related to me moving the folder somehow as I had issues with other programs when I did the HD move.

How can I completely wipe the data so that I can start from scratch? I can't seem to find where the settings and character data are being stored.

**Comment by Slazanger** [comment]
SMT saves data in my Documents\SMT if you delete this folder you will have a fresh start.

**Comment by john2288** [comment]
the number of times I scrolled past that because my brain merged it with my SVG folder..... thanks!
