### ISSUE TITLE
Electrical Storm in game shows as Plasma Storm in SMT

### ISSUE THREAD

**Issue by dmullaney** [Slazanger/SMT#79]
This was pretty annoying to learn in the field... 
![image](https://user-images.githubusercontent.com/2980194/140328013-d9b966fb-f75c-448b-8006-801a9780a533.png)

**Comment by tehraven** [comment]
I can confirm the tool's data -- There was, in fact, a **plasma storm** covering that location at the time.

This is not an SMT bug. Looking at the dependency data source...

**Comment by tehraven** [comment]
A81 confirmed Plasma storm in-game. Logged in a camper in that area and went over. Plasma.

![image](https://user-images.githubusercontent.com/171092/140335561-ab97b74a-32f5-4104-bc3c-1a3c1b608f41.png)

**Comment by dmullaney** [comment]
I mean... the screenshot is pretty clear... its an electrical storm...

**Comment by tehraven** [comment]
The screenshot shows you the one piece of UI that is **consistently incorrect about storms**

**Comment by tehraven** [comment]
Also you should know that there isn't an API (nor even an in-game via map feature) that tells you what actual storms are being rendered in what systems. There's a third party, Eve-Scout-like, service that lists the storms main system.

SMT takes that and does the +3 weak range around it. and it does it accurately.

The third party site lists A81 as the epicenter, and as a Plasma storm.
EVE Map lists the storm (no type provided) at A81, and traveling there shows a Plasma storm.

**Comment by dmullaney** [comment]
I also couldn't cloak...

**Comment by tehraven** [comment]
I'm not trying to disprove what you experienced... I'm telling you there's nothing SMT nor anyone else can do about it.

The game only tells you there's a Storm there, via the Map. You get, at the least, the same bit of information from SMT. I understand that it mislead you but the only thing we can do is report on the data available, and the data available says Plasma.

Here's the aforementioned 3rd party. https://evescoutrescue.com/home/stormtrack.php

What are you suggesting SMT does here? It could remove storm types (and be a huge degradation of service -- one that has been functionally critical for hunting in the past and very, very accurate thanks to Eve Scout)
