### ISSUE TITLE
Enhancement: Intel filter pattern

### ISSUE THREAD

**Issue by chrRtg** [Slazanger/SMT#8]
We use in various Intel messages like “Jita clr” or "“Jita clear” to indicate all neuts have left a system.

SMT will recognize this message as a regular intel massage and show the system as contaminated. But in fact the opposite is meant.

May I suggest to add some strings - or even better patterns - as “system clear” identifiers, e.g. to a IntelClear.txt file? If such string appear together with a system name in a intel SMT will consider this as a system clear identifier.

**Comment by Slazanger** [comment]
implemented in 0.55
