### ISSUE TITLE
No warning sound in Windows 11?

### ISSUE THREAD

**Issue by Midnight-Vortex** [Slazanger/SMT#80]
Hi,

I've upgraded to Win11 and since then I don't get the warning chime "woop.mp3" anymore.
Can someone cross check that for me?

Thanks!
Kind Regards
Blackhearts

**Comment by bytewind** [comment]
Where do you store that? If it's local your corpmates can't access it, and if it's online who pays for the hosting?

**Comment by Slazanger** [comment]
Do you have the windows media subsystem component installed ? some people remove it thinking they don't need it

**Comment by Midnight-Vortex** [comment]
You mean Windows Media Player?

**Comment by Slazanger** [comment]
Not the media player itself, the windows media player component; it part of windows; i've seen people remove it; thinking its unneeded.

**Comment by Midnight-Vortex** [comment]
i have installed windows media player feature and sound is working

**Comment by Slazanger** [comment]
that will have installed the underlying component alongside it
