### ISSUE TITLE
Intel Chat Window gone

### ISSUE THREAD

**Issue by felixgonschorek** [Slazanger/SMT#81]
Hi,
yesterday i wanted to re-arrange the ZKB-Feed Window and somehow managed to make the intel chat log disappear - i checked every setting, right clicked every tab and icon but could not manage to make it reappear.
Do I have to re-install SMT 1.08 or am I missing something obvious?
Thanks!
![image](https://user-images.githubusercontent.com/5189941/152645358-1e4c288e-b02e-4325-adbb-ce46b7ddf202.png)

**Comment by Slazanger** [comment]
ive not added a layout reset yet; however you can do this manually; in My Documents\SMT\<Version> there will be a file "layout.dat" if you quit and delete it; it will reset back to the default layout
