### ISSUE TITLE
EVE client become unresponsive in large battles

### ISSUE THREAD

**Issue by mfp20** [Slazanger/SMT#82]
Is it possible that RMT locks log files for reading, making the eve client unresponsive?

Computer is a beefy desktop and I had no other tasks using cpu/gpu/ram; overall cpu utilization was at 15-20% and some single cores hitting 100% from time to time. But client was unable to cope with the large amount of actions happening in a 1500 pilots battle.

**Comment by Slazanger** [comment]
The log files are only opened in read only shared access. The biggest contribution to poor frame rate in huge fights is the audio in my experience.. I have to disable it to get reasonable frame rates
