### ISSUE TITLE
Intel not being parsed from logs.

### ISSUE THREAD

**Issue by Taiphoz** [Slazanger/SMT#88]
I have the correct path set, and in game I have log to file selected so the logs are there in the right place being saved to by the game, but for some reason smt wont parse the log files, is there an issue with this, is there anything I can do to try and track down whats going wrong ?

I have the right intel channels set as well , cant think of anything else to check.

**Comment by basvis** [comment]
I have the same issue, tried everything from re-adding the characters, restarting the client, forcing ESI update, but nothing helped. 
This issue started for me when I updated to version 1.09.

**Comment by Taiphoz** [comment]
Solved this by moving the install location, no clue why it had issues with the ssd but it did. working now basvis try moving where you install it.

**Comment by Slazanger** [comment]
its unlikely to be the SMT location, the log issues are usually either the client not logging to disk, or onedrive interacting strangely
