### ISSUE TITLE
Waypoint/destination setting

### ISSUE THREAD

**Issue by escequi** [Slazanger/SMT#9]
Hello, are those functions not implemented yet? Here they're grey'd out

**Comment by Slazanger** [comment]
yes, you need to auth a character with ESI and then select the character in the character dropdown box

**Comment by escequi** [comment]
Sorry yea i looked for that option but couldn't find it?

**Comment by Slazanger** [comment]
if you go to the characters section and click "add character" then follow the login auth

**Comment by escequi** [comment]
![image](https://user-images.githubusercontent.com/11319347/39970278-f1c3ff46-56be-11e8-8693-bf8eda35980b.png)

**Comment by escequi** [comment]
I get this whenever i click the typing area

**Comment by Slazanger** [comment]
you need to add the registry fix..

**Comment by escequi** [comment]
Okay thanks for the help :p
