### ISSUE TITLE
Make the map follow the tracked player and keep the tracked player in view when the map is zoomed.

### ISSUE THREAD

**Issue by Taiphoz** [Slazanger/SMT#90]
I use SMT in small window so that it fits in my free screen space alongside my eve-o windows, as a result I often zoom the map to have a clearer view of the immediate systems around my tracked character.

It would be really cool for example if I have a zoom level of 50% the tool would always ensure that the tracked system is in view, as cantered as possible in the map window, thinking of it like a retro game you want the map to follow the character but you dont want the map to slide beyond its limits so you end up with a bunch of negative space not being used.

**Comment by Slazanger** [comment]
This will be in 1.10
