### ISSUE TITLE
Thera Connections Tab Duplicating Results

### ISSUE THREAD

**Issue by Plinopeo** [Slazanger/SMT#94]
Whenever the "Update Connections" button is pressed on the Thera Connections tab, the results are not refreshed but rather printed in whole below the previous connections.
![TheraProblem](https://user-images.githubusercontent.com/107890672/174678028-2ea6f3dc-0ec0-4935-ad2a-bfd967240523.PNG)

**Comment by Slazanger** [comment]
this was fixed in 1.11
