### ISSUE TITLE
Can not exectude in win11

### ISSUE THREAD

**Issue by zeiyu314** [Slazanger/SMT#96]
The version is SMT1.12
When i'm trying to run it, it's nothing heppen.
The SMT 1.09 can work, but didn't support the esi function.

**Comment by cbrothers** [comment]
I had a friend that had the same issue, until he installed a newer version of .NET.   try installing v6

https://dotnet.microsoft.com/en-us/download

**Comment by Slazanger** [comment]
you need both the runtime and the desktop runtime

**Comment by zeiyu314** [comment]
> 我有一个朋友有同样的问题，直到他安装了较新版本的.NET。尝试安装 v6
> 
> https://dotnet.microsoft.com/en-us/download
> 
> Slaz甚至在他的discord服务器 https://discord.com/channels/546453460531413002/546453460988461072/982920344400703538

tks, friend, it works now.
