### ISSUE TITLE
Unable to track the position of pilot by esi.

### ISSUE THREAD

**Issue by zeiyu314** [Slazanger/SMT#97]
![image](https://user-images.githubusercontent.com/44489550/187401249-ce79cb7c-19f2-4e93-835a-6815da4c7e39.png)
After adding an pilot with the esi, then it will not shows the position and the name of polit.
OS Windows 11, SMT version 108~112

**Comment by Slazanger** [comment]
Is this still occurring ?

**Comment by Slazanger** [comment]
this occurs every now and then;  occasionally ESI gets stuck and you need to wait for it to fix itself #ccpls , in this case you already have the option to revert to log based tracking so closing this
